In [1]:
import requests
import bs4
import pandas as pd
import time

def make_price_dataframe(code, timeframe, count):
    url = 'https://fchart.stock.naver.com/sise.nhn?requestType=0'
    price_url = url + '&symbol=' + code + '&timeframe=' + timeframe + '&count=' + count
    
    price_data = requests.get(price_url)
    price_data_bs = bs4.BeautifulSoup(price_data.text, 'html')
    item_list = price_data_bs.findAll('item')
    
    date_list = []
    price_list = []

    for item in item_list:
        temp_data = item['data']
        datas = temp_data.split('|')
        date_list.append(datas[0])
        price_list.append(datas[4])
    
    price_df = pd.DataFrame({code:price_list}, index=date_list)
    
    return price_df

In [7]:
make_price_dataframe('219480','day','37')

         219480
20200522  13955
20200525  14185
20200526  14385
20200527  14380
20200528  14535
20200529  14450
20200601  14545
20200602  14555
20200603  14750
20200604  14860
20200605  14965
20200608  15215
20200609  15365
20200610  15355
20200611  14980
20200612  14490
20200615  14020
20200616  14805
20200617  14955
20200618  14815
20200619  14910
20200622  14690
20200623  14900
20200624  14900
20200625  14515
20200626  14660
20200629  14395
20200630  14535
20200701  14730
20200702  14880
20200703  14995
20200706  15140
20200707  15110
20200708  14970
20200709  15110
20200710  14895
20200713  15280