In [3]:
import pandas as pd
import time
import StockPrice

In [4]:
path = './data/stocks.tsv'
code_data = pd.read_csv(path, sep='\t')
code_data = code_data[['종목코드','종목명']]

def make_code2(x):
    x = str(x)
    return '0' * (6 - len(x)) + x

code_data['종목코드'] = code_data['종목코드'].apply(make_code2)

In [5]:
# code_data

     종목코드                    종목명
0  219480    KODEX 미국S&P500선물(H)
1  195970  ARIRANG 선진국MSCI(합성 H)
2  132030          KODEX 골드선물(H)
3  308620         KODEX 미국채10년선물
4  152380          KODEX 국채선물10년
5  153130             KODEX 단기채권

In [6]:
for num, code in enumerate(code_data['종목코드']):
    try:
        print(num, code)
        time.sleep(1)

        try:
            price_df = StockPrice.make_price_dataframe(code, 'day', '37')
        except requests.exceptioins.Timeout:
            time.sleep(60)
            price_df = StockPrice.make_price_dataframe(code, 'day', '37')
        
        if num == 0:
            total_price = price_df
        else:
            total_price = pd.merge(total_price, price_df, how='outer', right_index=True, left_index=True)
        
    except ValueError:
        continue
    except KeyError:
        continue

0 219480
1 195970
2 132030
3 308620
4 152380
5 153130

In [8]:
total_price.index = pd.to_datetime(total_price.index)

In [9]:
# total_price

           219480 195970 132030 308620 152380  153130
2020-05-22  13955   8710  12260  12830  72780  102305
2020-05-25  14185   8720  12240  12875  72990  102310
2020-05-26  14385   8930  12275  12800  72900  102315
2020-05-27  14380   9005  12055  12780  72820  102320
2020-05-28  14535   9065  12140  12830  72805  102350
2020-05-29  14450   9155  12140  12825  72630  102370
2020-06-01  14545   9155  12320  12710  72555  102370
2020-06-02  14555   9320  12255  12700  72565  102370
2020-06-03  14750   9490  12120  12595  72320  102360
2020-06-04  14860   9595  11950  12560  72295  102360
2020-06-05  14965   9640  12020  12400  72165  102360
2020-06-08  15215   9755  11910  12330  72160  102360
2020-06-09  15365   9820  11925  12290  72505  102360
2020-06-10  15355   9735  12100  12235  72500  102365
2020-06-11  14980   9665  12190  12375  72575  102375
2020-06-12  14490   9375  12190  12485  72540  102365
2020-06-15  14020   9155  12090  12625  72340  102360
2020-06-16  14805   9455  12125  12470  72460  102360
2020-06-17  14955   9560  12175  12545  72370  102360
2020-06-18  14815   9520  12165  12485  72640  102360
2020-06-19  14910   9525  12200  12525  72615  102365
2020-06-22  14690   9530  12375  12560  72530  102370
2020-06-23  14900   9530  12380  12500  72585  102380
2020-06-24  14900   9660  12520  12415  72715  102385
2020-06-25  14515   9405  12450  12490  72820  102390
2020-06-26  14660   9445  12410  12450  72940  102390
2020-06-29  14395   9365  12525  12445  72690  102390
2020-06-30  14535   9390  12530  12505  72695  102390
2020-07-01  14730   9380  12635  12495  72420  102390
2020-07-02  14880   9460  12450  12450  72615  102405
2020-07-03  14995   9580  12515  12450  72575  102410
2020-07-06  15140   9590  12510  12400  72425  102410
2020-07-07  15110   9690  12580  12405  72550  102415
2020-07-08  14970   9580  12670  12410  72650  102415
2020-07-09  15110   9625  12770  12425  72565  102420
2020-07-10  14895   9480  12635  12540  72535  102420
2020-07-13  15280   9690  12705  12475  72430  102420